from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config

# !!!! SELECT MODE !!!!
MODE = config("MODE")

# Close all open positions and orders
ABORT_ALL_POSITIONS = config("ABORT_ALL_POSITIONS", cast=bool)

# Find Cointegrated Pairs
FIND_COINTEGRATED = config("FIND_COINTEGRATED", cast=bool)

# Manage Exits
MANAGE_EXITS = config("MANAGE_EXITS", cast=bool)

# Place Trades
PLACE_TRADES = config("PLACE_TRADES", cast=bool)

# Resolution
RESOLUTION = config("RESOLUTION", cast=int)

# Thresholds - Opening
ZSCORE_THRESH = config("ZSCORE_THRESH", cast=float)
LEVERAGE = config("LEVERAGE", cast=int)

# Thresholds - Closing
CLOSE_AT_ZSCORE_CROSS = config("CLOSE_AT_ZSCORE_CROSS", cast=bool)

# Ethereum Address
ETHEREUM_ADDRESS = config("ETHEREUM_ADDRESS")

# KEYS - PRODUCTION
# Must be on Mainnet in DYDX
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# KEYS - DEVELOPMENT
# Must be on Testnet in DYDX
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# KEYS - Export
STARK_PRIVATE_KEY = (
    STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
)
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = (
    DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
)
DYDX_API_PASSPHRASE = (
    DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET
)

# HOST - Export
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_GOERLI

# HTTP PROVIDER
HTTP_PROVIDER_MAINNET = (
    "https://eth-mainnet.g.alchemy.com/v2/Z3vZqWcSmseceeFsIakT0sgiiizdXHy8"
)
HTTP_PROVIDER_TESTNET = (
    "https://eth-goerli.g.alchemy.com/v2/gx_YPJc6PjPigcf1qb8k76Sp44YUJLVI"
)
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET
